# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username:

# development:
#   <<: *default
#   database: news_feed_development

# test:
#   <<: *default
#   database: news_feed_test


