# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:

development:
  <<: *default
  database: news_feed_development

test:
  <<: *default
  database: news_feed_test


